# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "80:5601"    # Kibana
    - "9200:9200"  # ElasticSearch
    - "5044:5044"  # Filebeat
    - "5000:5000"  # Lumberjack
